### ISSUE TITLE
url extraction fails

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.awol#18]
```
$ nosetests
.F..
======================================================================
FAIL: Ensure class parse method gets all desired fields.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/paregorios/Envs/isaw.awol/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/paregorios/Documents/files/I/isaw.awol/isaw/awol/tests/test_awol_article.py", line 49, in test_awol_article_init
    assert_equals(r.url, 'http://www.unimc.it/riviste/index.php/cap-cult/index')
AssertionError: 'http://www.unimc.it/riviste/index.php/cap-cult/issue/view/18' != 'http://www.unimc.it/riviste/index.php/cap-cult/index'
-------------------- >> begin captured logging << --------------------
langid.langid: INFO: initializing identifier
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 4 tests in 0.946s

FAILED (failures=1)
```

**Comment by paregorios** [comment]
fixed with f85a527fd7e0fb4c3a420bdb344cd38ed5c5603f
