### ISSUE TITLE
walk_to_json.py fails with unexpected category tag "EES"

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.awol#82]
Running ```bin/walk_to_json.py``` on February 2017 blog content, I get the following traceback:

ERROR:_parse_keywords:unexpected category tag "EES" in post with title "The Egypt Exploration Society YouTube Channel"
ERROR, UNEXPECTED EXCEPTION

```
Traceback (most recent call last):
  File "bin/walk_to_json.py", line 228, in <module>
    main(args)
  File "bin/walk_to_json.py", line 36, in inner
    return func(*args, **kwargs)
  File "bin/walk_to_json.py", line 73, in main
    resources = parsers.parse(a)
  File "/Users/paregorios/Documents/files/I/isaw.awol/bin/../isaw/awol/parse/awol_parsers.py", line 72, in parse
    return parser.parse(article)
  File "/Users/paregorios/Documents/files/I/isaw.awol/bin/../isaw/awol/parse/awol_parse.py", line 253, in parse
    resources = self._get_resources(article)
  File "/Users/paregorios/Documents/files/I/isaw.awol/bin/../isaw/awol/parse/awol_parse.py", line 662, in _get_resources
    primary_resource = self._get_primary_resource(article)
  File "/Users/paregorios/Documents/files/I/isaw.awol/bin/../isaw/awol/parse/awol_parse.py", line 547, in _get_primary_resource
    keywords = self._parse_keywords(article.title, titles[-1], article.categories)
  File "/Users/paregorios/Documents/files/I/isaw.awol/bin/../isaw/awol/parse/awol_parse.py", line 995, in _parse_keywords
    raise Exception
Exception
```

**Comment by paregorios** [comment]
There are a number of new category strings, and some new typos for old ones. I'm working through them, adding to [the authority list](https://github.com/isawnyu/isaw.awol/blob/master/isaw/awol/awol_title_strings.csv).

**Comment by paregorios** [comment]
Code in branch "issue82" at commit is believed to resolve this issue. Tests run clean. After a full run of ```walk_to_json``` without keyword-related errors, I will issue a pull request to merge these changes to master.
